# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm run test --watch=false --code-coverage
  displayName: 'npm install, build and test'

- task: PublishTestResults@2
  displayName: 'Publish Unit test Results'
  inputs:
    searchFolder: '$(System.DefaultWorkingDirectory)/unittests/junit'
    testResultsFormat: 'JUnit'
    testResultsFiles: "**/TESTS-*.xml"
    testRunTitle: 'Angular'
    
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **\*.js
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'